version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: mugtaram/yamdb:latest
    restart: always
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on: 
      - db
    env_file: 
      - ./.env

  nginx:
    image: nginx:1.19.5
    restart: always
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
      - ./config/nginx/:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web
    env_file:
      - ./.env
    