version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: mugatram/yamdb:latest
    restart: always
    volumes:
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on: 
      - db
    env_file: 
      - ./.env

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - static_volume:/static
      - ./config/nginx/:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web
    env_file:
      - ./.env
    